### ISSUE TITLE
Implement management of K8s service

### ISSUE THREAD

**Issue by elouanKeryell-Even** [gisaia/ARLAS-subscriptions#89]
# Description

- Create GitHub private repo `arlas-subscriptions-integration`
- Implement python CLI tool `arlas-subscriptions`, in repo `arlas-subscriptions-integration`
  - `arlas-subscriptions create` should create a GKE cluster, in version 1.11
  - `arlas-subscriptions delete` should delete a GKE cluster
  - Google Cloud project, Google Cloud zone and Kubernetes versions can be hard-coded
    - See with @alainbodiguel what Google Cloud project we are going to use
- CLI tool `arlas-subscriptions` should be containerized using Docker, to avoid forcing user to install specific version of kubectl, helm, etc ... used by the project

## Authentication to Kubernetes

`arlas-subscriptions create` should implement authentication to cluster, something equivalent to `gcloud container cluster get-credentials` but in python. It should register cluster + credentials in `~/.kube/config`

Method [get_cluster()](https://googleapis.dev/python/container/latest/gapic/v1/api.html#google.cloud.container_v1.ClusterManagerClient.get_cluster) of the GKE python API should be used to:

- get [cluster object](https://googleapis.dev/python/container/latest/gapic/v1/types.html#google.cloud.container_v1.types.Cluster), which contains all information to fill the `~/.kube/config`

Here is what sub-object `cluster.master_auth` looks like:

```yaml
username: <redacted>
password: <redacted>
cluster_ca_certificate: <redacted>
client_certificate: <redacted>
client_key: <redacted>
```

Based on my local `~/.kube/config` file, here is what the `~/.kube/config` file we will build will have to look like:

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <cluster.master_auth.cluster_ca_certificate>
    server: https://<cluster.endpoint>
  name: arlas-subscriptions-integration
contexts:
- context:
    cluster: arlas-subscriptions-integration
    user: arlas-subscriptions-integration
  name: arlas-subscriptions-integration
current-context: arlas-subscriptions-integration
kind: Config
preferences: {}
users:
- name: arlas-subscriptions-integration
  user:
    client-certificate: <cluster.master_auth.client_certificate>
    client-key: <cluster.master_auth.client_key>
```

# Test process

```bash
./arlas-subscriptions-integration create
gcloud container clusters list
./arlas-subscriptions-integration delete
gcloud container clusters list
```
